## Write a Numpy program to compute the multiplication of two given matrixes

In [9]:
import numpy as np
a=[[1,2,3],[4,5,6],[5,6,1]]
b=[[5,6,7],[8,9,10],[1,2,3]]

In [10]:

np.dot(a,b)

array([[24, 30, 36],
       [66, 81, 96],
       [74, 86, 98]])

## Write a NumPy program to compute the determinant of a given square array

In [12]:
a=a=[[1,2,3],[4,5,6],[5,6,1]]
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36],
       [25, 36,  1]], dtype=int32)

## Write a NumPy program to compute the cross product of two given vectors

In [14]:
a = [[1, 3], [4, 1]]
b = [[1, 2], [3,5]]
np.cross(a, b)

array([-1, 17])

## Write a NumPy program to compute the condition number of a given matrix

In [15]:
matrix = [[4, 2], [3, 1]]
  
np.linalg.cond(matrix)
  

14.933034373659256

## Write a NumPy program to compute the inverse of a given matrix

In [16]:
m = [[1,2],[3,4]]

np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])